from abc import ABC, abstractmethod

# Abstract Module class
class Module(ABC):
    @abstractmethod
    def getCategory(self): ...
        
    @abstractmethod
    def getVersionNumber(self): ...
    
    @abstractmethod
    def process(self, workspace): ...
    
    @abstractmethod
    def initialiseParameters(self): ...
    
    @abstractmethod
    def updateAndGetParameters(self): ...
    
    @abstractmethod
    def updateAndGetImageMeasurementRefs(self): ...
    
    @abstractmethod
    def updateAndGetObjectMeasurementRefs(self): ...
    
    @abstractmethod
    def updateAndGetObjectMetadataRefs(self): ...
    
    @abstractmethod
    def updateAndGetMetadataReferences(self): ...
            
    @abstractmethod
    def updateAndGetParentChildRefs(self): ...
            
    @abstractmethod
    def updateAndGetPartnerRefs(self): ...
            
    @abstractmethod
    def verify(self): ...
            
    @abstractmethod
    def execute(self, workspace): ...
            
    @abstractmethod
    def addObjectMeasurementRef(self, ref): ...
            
    @abstractmethod
    def addObjectMetadataRef(self, ref): ...
            
    @abstractmethod
    def getImageMeasurementRef(self, name): ...
            
    @abstractmethod
    def addImageMeasurementRef(self, ref): ...
            
    @abstractmethod
    def getObjectMeasurementRef(self, name): ...
            
    @abstractmethod
    def getObjectMetadataRef(self, name): ...
            
    @abstractmethod
    def getMetadataRef(self, name): ...
            
    @abstractmethod
    def addMetadataRef(self, ref): ...
            
    @abstractmethod
    def getParentChildRef(self, parentName, childName): ...
            
    @abstractmethod
    def addParentChildRef(self, ref): ...
            
    @abstractmethod
    def addPartnerRef(self, ref): ...
            
    @abstractmethod
    def getParameter(self, name): ...
            
    @abstractmethod
    def updateParameterValue(self, name, value): ...
            
    @abstractmethod
    def getParameterValue(self, name, workspace): ...
            
    @abstractmethod
    def setParameterVisibility(self, name, visible): ...
            
    @abstractmethod
    def getAllParameters(self): ...
            
    @abstractmethod
    def invalidParameterIsVisible(self): ...
            
    @abstractmethod
    def getParametersMatchingType(self, type): ...
            
    @abstractmethod
    def addParameterGroupParameters(self, parameterGroup, type, parameters): ...
            
    @abstractmethod
    def getModules(self): ...
            
    @abstractmethod
    def setModules(self, modules): ...
            
    @abstractmethod
    def hasParameter(self, parameterName): ...
            
    @abstractmethod
    def getModuleID(self): ...
            
    @abstractmethod
    def setModuleID(self, moduleID): ...
            
    @abstractmethod
    def getShortDescription(self): ...
            
    @abstractmethod
    def getNotes(self): ...
            
    @abstractmethod
    def setNotes(self, notes): ...
            
    @abstractmethod
    def isEnabled(self): ...
            
    @abstractmethod
    def setEnabled(self, enabled): ...
            
    @abstractmethod
    def canBeDisabled(self): ...
            
    @abstractmethod
    def setCanBeDisabled(self, canBeDisabled): ...
            
    @abstractmethod
    def canShowProcessingTitle(self): ...
            
    @abstractmethod
    def setShowProcessingViewTitle(self, showProcessingViewTitle): ...
            
    @abstractmethod
    def isVerbose(self): ...
            
    @abstractmethod
    def setVerbose(self, verboseIn): ...
            
    @abstractmethod
    def canShowOutput(self): ...
            
    @abstractmethod
    def setShowOutput(self, showOutput): ...
            
    @abstractmethod
    def isRunnable(self): ...
            
    @abstractmethod
    def setRunnable(self, runnable): ...
            
    @abstractmethod
    def isReachable(self): ...
            
    @abstractmethod
    def setReachable(self, reachable): ...
            
    @abstractmethod
    def isDeprecated(self): ...
            
    @abstractmethod
    def setDeprecated(self, deprecated): ...
            
    @abstractmethod
    def getIL2Support(self): ...
            
    @abstractmethod
    def getRedirectModuleID(self, workspace): ...
            
    @abstractmethod
    def setRedirectModuleID(self, redirectModuleID): ...
            
    @abstractmethod
    def hasVisibleParameters(self): ...
            
    @abstractmethod
    def duplicate(self, newModules, copyID): ...
            
    @abstractmethod
    def writeStatus(self, message): ...
            
    @abstractmethod
    def writeProgressStatus(self, count, total, featureBeingProcessed): ...
