from typing import Iterator, TypeVar, Generic

from types.JPoint import JPoint

# Type variable for Point<Integer> — in Python we just represent Integer as int
T = TypeVar("T", bound=int)


class JCoordinateSetFactoryType:
    def getName(self) -> str: ...
    def createCoordinateSet(self) -> JCoordinateSetType: ...
    def duplicate(self) -> JCoordinateSetFactoryType: ...


class JCoordinateSetType(Generic[T]):
    """Python type stub for io.github.mianalysis.mia.object.coordinates.volume.CoordinateSetI"""

    # --- Methods defined in the interface ---
    def getFactory(self) -> JCoordinateSetFactoryType: ...
    def addCoord(self, x: int, y: int, z: int) -> bool: ...
    def finalise(self) -> None: ...
    def finaliseSlice(self, z: int) -> None: ...
    def getNumberOfElements(self) -> int: ...
    def getSlice(self, slice: int) -> "JCoordinateSetType[T]": ...
    def createEmptyCoordinateSet(self) -> "JCoordinateSetType[T]": ...
    def duplicate(self) -> "JCoordinateSetType[T]": ...
    def calculateProjected(self) -> "JCoordinateSetType[T]": ...
    def iterator(self) -> Iterator[JPoint[int]]: ...
    def contains(self, point: JPoint[int]) -> bool: ...

    # --- Default methods (implemented in the interface itself) ---
    def calculateSurface(self, is2D: bool) -> "JCoordinateSetType[T]": ...
    def calculateSurface2D(self) -> "JCoordinateSetType[T]": ...
    def calculateSurface3D(self) -> "JCoordinateSetType[T]": ...
