# Listing the methods, but to avoid annotating yet more Java classes (for now), annotating any unknown classes as Any
from typing import Any, List, Optional

class JFileType:
    # Constructors
    def __init__(self, pathname: str): ...
    def __init__(self, parent: str, child: str): ...
    def __init__(self, parent: JFileType, child: str): ...
    def __init__(self, uri: Any): ...

    # Static constants
    separatorChar: str
    separator: str
    pathSeparatorChar: str
    pathSeparator: str

    # Methods
    def getName(self) -> str: ...
    def getParent(self) -> Optional[str]: ...
    def getParentFile(self) -> Optional[JFileType]: ...
    def getPath(self) -> str: ...
    def isAbsolute(self) -> bool: ...
    def getAbsolutePath(self) -> str: ...
    def getAbsoluteFile(self) -> JFileType: ...
    def getCanonicalPath(self) -> str: ...
    def getCanonicalFile(self) -> JFileType: ...
    def canRead(self) -> bool: ...
    def canWrite(self) -> bool: ...
    def exists(self) -> bool: ...
    def isDirectory(self) -> bool: ...
    def isFile(self) -> bool: ...
    def isHidden(self) -> bool: ...
    def lastModified(self) -> int: ...
    def length(self) -> int: ...
    def createNewFile(self) -> bool: ...
    def delete(self) -> bool: ...
    def deleteOnExit(self) -> None: ...
    def list(self) -> Optional[List[str]]: ...
    def list(self, filter: Optional[Any]) -> Optional[List[str]]: ...
    def listFiles(self) -> Optional[List[JFileType]]: ...
    def listFiles(self, filter: Optional[Any]) -> Optional[List[JFileType]]: ...
    def listFiles(self, filter: Optional[Any]) -> Optional[List[JFileType]]: ...
    def mkdir(self) -> bool: ...
    def mkdirs(self) -> bool: ...
    def renameTo(self, dest: JFileType) -> bool: ...
    def setLastModified(self, time: int) -> bool: ...
    def setReadOnly(self) -> bool: ...
    def setWritable(self, writable: bool, ownerOnly: bool = ...) -> bool: ...
    def setReadable(self, readable: bool, ownerOnly: bool = ...) -> bool: ...
    def setExecutable(self, executable: bool, ownerOnly: bool = ...) -> bool: ...
    def canExecute(self) -> bool: ...
    @staticmethod
    def listRoots() -> List[JFileType]: ...
    def getTotalSpace(self) -> int: ...
    def getFreeSpace(self) -> int: ...
    def getUsableSpace(self) -> int: ...
    def compareTo(self, pathname: JFileType) -> int: ...
    def toURI(self) -> Any: ...
    def toURL(self) -> Any: ...
    def __str__(self) -> str: ...