from __future__ import annotations
from typing import ClassVar

from src.types.JColor import JColor
from src.types.JImagePlus import JImagePlus
from src.types.JIndexColorModel import JIndexColorModel

class JLUT:
    def clone(self) -> JLUT: ...
    def createInvertedLut(self) -> JLUT: ...

    @staticmethod
    def createLutFromColor(color: JColor) -> JLUT: ...

    def getBytes(self) -> bytes: ...
    def getColorModel(self) -> JIndexColorModel: ...

    @staticmethod
    def LutsDiffer(imp1: JImagePlus, imp2: JImagePlus) -> bool: ...

    def toString(self) -> str: ...