from __future__ import annotations
from typing import Protocol,TypeVar

T = TypeVar("T", bound=float)  # Python equivalent for Java's Number

class JPointType(Protocol[T]):
    """Python type stub for io.github.mianalysis.mia.object.coordinates.Point"""

    x: T
    y: T
    z: T

    # --- Constructors ---
    def __init__(self, x: T, y: T, z: T) -> None: ...

    # --- Accessors ---
    def getX(self) -> T: ...
    def getY(self) -> T: ...
    def getZ(self) -> T: ...

    # --- Mutators ---
    def setX(self, x: T) -> None: ...
    def setY(self, y: T) -> None: ...
    def setZ(self, z: T) -> None: ...

    # --- Utility methods ---
    def calculateDistanceToPoint(self, point: JPointType[T]) -> float: ...
    def calculateAngle2D(self, point: JPointType[T]) -> float: ...
    def hashCode(self) -> int: ...
    def equals(self, obj: object) -> bool: ...
    def duplicate(self) -> JPointType[T]: ...
    def compareTo(self, point: JPointType[T]) -> int: ...
    def toString(self) -> str: ...
