# Listing the methods, but to avoid annotating yet more Java classes (for now), annotating any unknown classes as Any
from __future__ import annotations

from src.types.JSpatiallyCalibratedType import JSpatiallyCalibrated

class JSpatioTemporallyCalibrated(JSpatiallyCalibrated):
    # Methods
    def getNFrames(self) -> int: ...
    def setNFrames(self, n_frames: int): ...
    def getFrameInterval(self) -> float: ...
    def setFrameInterval(self, frame_interval: float): ...
    def getTimeUnit(self): ...
    def setTimeUnit(self, time_unit): ...
    def applySpatioTemporalCalibrationToImage(self, ipl): ...
    def setSpatioTemporalCalibrationFromExample(self, example: JSpatioTemporallyCalibrated): ...
    