# Listing the methods, but to avoid annotating yet more Java classes (for now), annotating any unknown classes as Any
from __future__ import annotations

class JSpatiallyCalibrated:
    # Methods
    def getName(self) -> str: ...
    def getWidth(self: JSpatiallyCalibrated) -> int: ...
    def setWidth(self: JSpatiallyCalibrated, width: int): ...
    def getHeight(self: JSpatiallyCalibrated) -> int: ...
    def setHeight(self: JSpatiallyCalibrated, height: int): ...
    def getNSlices(self: JSpatiallyCalibrated) -> int: ...
    def setNSlices(self: JSpatiallyCalibrated, n_slices: int): ...
    def getDppXY(self: JSpatiallyCalibrated) -> float: ...
    def setDppXY(self: JSpatiallyCalibrated, dpp_xy: float): ...
    def getDppZ(self: JSpatiallyCalibrated) -> float: ...
    def setDppZ(self: JSpatiallyCalibrated, dpp_z: float): ...
    def getSpatialUnits(self: JSpatiallyCalibrated) -> str: ...
    def setSpatialUnits(self: JSpatiallyCalibrated, spatial_units: str): ...
    def applySpatialCalibrationToImage(self: JSpatiallyCalibrated, ipl): ...
    def setSpatialCalibrationFromExample(self: JSpatiallyCalibrated, example: JSpatiallyCalibrated): ...