# Listing the methods, but to avoid annotating yet more Java classes (for now), annotating any unknown classes as Any
from __future__ import annotations

class JSpatiallyCalibrated:
    # Methods
    def getName(self) -> str: ...
    def getWidth(self) -> int: ...
    def setWidth(self, width: int): ...
    def getHeight(self) -> int: ...
    def setHeight(self, height: int): ...
    def getNSlices(self) -> int: ...
    def setNSlices(self, n_slices: int): ...
    def getDppXY(self) -> float: ...
    def setDppXY(self, dpp_xy: float): ...
    def getDppZ(self) -> float: ...
    def setDppZ(self, dpp_z: float): ...
    def getSpatialUnits(self) -> str: ...
    def setSpatialUnits(self, spatial_units: str): ...
    def applySpatialCalibrationToImage(self, ipl): ...
    def setSpatialCalibrationFromExample(self, example: JSpatiallyCalibrated): ...