from __future__ import annotations
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from src.objects.coordinateset import (
        CoordinateSet,
        CoordinateSetIterator,
        CoordinateSetFactory,
    )
    from src.utilities.types import Point, Points
    from types.JPointType import JPointType

class CoordinateSetWrapper:
    _coordinate_set: CoordinateSet

    def __init__(self) -> None: ...
    def getPythonCoordinateSet(self) -> CoordinateSet: ...
    def setPythonCoordinateSet(self, coordinate_set: CoordinateSet) -> None: ...
    def getPythonPoints(self) -> Points: ...
    def getPythonPointAtIndex(self, idx: int) -> Point: ...
    def getPointAtIndex(self, idx: int) -> JPointType[int]: ...
    def getFactory(self) -> CoordinateSetFactoryWrapper: ...
    def addCoord(self, x: int, y: int, z: int) -> bool: ...
    def getNumberOfElements(self) -> int: ...
    def createEmptyCoordinateSet(self) -> CoordinateSetWrapper: ...
    def finalise(self) -> None: ...
    def finaliseSlice(self, z: int) -> None: ...
    def duplicate(self) -> CoordinateSetWrapper: ...
    def calculateProjected(self) -> CoordinateSetWrapper: ...
    def getSlice(self, slice: int) -> CoordinateSetWrapper: ...
    def size(self) -> int: ...
    def iterator(self) -> CoordinateSetIterator: ...
    def isEmpty(self) -> bool: ...
    def toArray(self, array: Any | None = None) -> Any: ...
    def contains(self, point: Point) -> bool: ...
    def containsAll(self, points: Points) -> bool: ...
    def add(self, point: Point) -> bool: ...
    def addAll(self, points: Points) -> bool: ...
    def retainAll(self, points: Points) -> bool: ...
    def remove(self, point: Point) -> bool: ...
    def removeAll(self, points: Points) -> bool: ...
    def clear(self) -> None: ...
    def equals(self, point: Point) -> bool: ...
    def hashCode(self, point: Point) -> int: ...
    def spliterator(self) -> Any: ...


class CoordinateSetFactoryWrapper:
    _coordinate_set_factory: CoordinateSetFactory

    def __init__(self) -> None: ...
    def getPythonCoordinateSetFactory(self) -> CoordinateSetFactory: ...
    def setPythonCoordinateSetFactory(self, coordinate_set_factory: CoordinateSetFactory) -> None: ...
    def getName(self) -> str: ...
    def createCoordinateSet(self) -> CoordinateSetWrapper: ...
    def duplicate(self) -> CoordinateSetFactoryWrapper: ...
